### PR TITLE
feat: updates make target to generate display metadata as well

### PR DESCRIPTION
**Pull request by g-awmalik**

### CODE REVIEW

**Comment by g-awmalik** [comment]
@gtsorbo - the int test is complain about `project_id_standalone` but I see that as an output from the test setup config. Have you seen this before?

**Comment by g-awmalik** [comment]
Actually, here's the problem:

```
Error: Error enabling the Compute Engine API required to delete the default network: Error waiting for Enable Project "secure-cicd-singleproj-b5ff" Services: [compute.googleapis.com]: Error code 3, message: [service compute.googleapis.com encountered internal error: type: "googleapis.com" subject: "160009" ] with failed services [compute.googleapis.com]
```

b/284117246 & b/283908020 for context.

**Review by gtsorbo — APPROVED** [review]

**Pull request merged**
